sonar.projectKey=TruvideoCapacitorVideoSdk
sonar.projectName=TruvideoCapacitorVideoSdk
sonar.projectVersion=1.0

# Token you created earlier
sonar.login=sqp_44e2f31ff93a172b79adbbfef93b29040c3c638b

# Source code folder
sonar.sources=src

# Ignore build files + Capacitor native folders
sonar.exclusions=**/node_modules/**, **/build/**, **/dist/**, android/**, ios/**

# Optional - for React test coverage (if using Jest)
sonar.javascript.lcov.reportPaths=coverage/lcov.info
